// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cs.ut.security;

import cs.ut.security.Authorities;

privileged aspect Authorities_Roo_JavaBean {
    
    public String Authorities.getAuthority() {
        return this.authority;
    }
    
    public void Authorities.setAuthority(String authority) {
        this.authority = authority;
    }
    
}
