// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cs.ut.domain;

import cs.ut.domain.Plant;
import cs.ut.domain.PlantDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PlantDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PlantDataOnDemand: @Component;
    
    private Random PlantDataOnDemand.rnd = new SecureRandom();
    
    private List<Plant> PlantDataOnDemand.data;
    
    public Plant PlantDataOnDemand.getNewTransientPlant(int index) {
        Plant obj = new Plant();
        setDescription(obj, index);
        setIdentifier(obj, index);
        setName(obj, index);
        setPricePerDay(obj, index);
        return obj;
    }
    
    public void PlantDataOnDemand.setDescription(Plant obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void PlantDataOnDemand.setIdentifier(Plant obj, int index) {
        int identifier = index;
        obj.setIdentifier(identifier);
    }
    
    public void PlantDataOnDemand.setName(Plant obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void PlantDataOnDemand.setPricePerDay(Plant obj, int index) {
        float pricePerDay = new Integer(index).floatValue();
        obj.setPricePerDay(pricePerDay);
    }
    
    public Plant PlantDataOnDemand.getSpecificPlant(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Plant obj = data.get(index);
        Long id = obj.getId();
        return Plant.findPlant(id);
    }
    
    public Plant PlantDataOnDemand.getRandomPlant() {
        init();
        Plant obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Plant.findPlant(id);
    }
    
    public boolean PlantDataOnDemand.modifyPlant(Plant obj) {
        return false;
    }
    
    public void PlantDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Plant.findPlantEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Plant' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Plant>();
        for (int i = 0; i < 10; i++) {
            Plant obj = getNewTransientPlant(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
