// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cs.ut.domain;

import cs.ut.domain.PlantIntegrationTest;
import java.util.Iterator;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;

privileged aspect PlantIntegrationTest_Roo_IntegrationTest {
    
    @Test
    public void PlantIntegrationTest.testDelete() {
        Plant obj = dod.getRandomPlant();
        Assert.assertNotNull("Data on demand for 'Plant' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Plant' failed to provide an identifier", id);
        obj = plantRepository.findOne(id);
        plantRepository.delete(obj);
        plantRepository.flush();
        Assert.assertNull("Failed to remove 'Plant' with identifier '" + id + "'", plantRepository.findOne(id));
    }
    
}
