// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cs.ut.domain;

import cs.ut.domain.PurchaseOrderDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PurchaseOrderDataOnDemand_Roo_Configurable {
    
    declare @type: PurchaseOrderDataOnDemand: @Configurable;
    
}
