// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cs.ut.domain;

import cs.ut.domain.PurchaseOrderUpdate;
import cs.ut.domain.PurchaseOrderUpdateDataOnDemand;
import cs.ut.domain.PurchaseOrderUpdateIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PurchaseOrderUpdateIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PurchaseOrderUpdateIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PurchaseOrderUpdateIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PurchaseOrderUpdateIntegrationTest: @Transactional;
    
    @Autowired
    PurchaseOrderUpdateDataOnDemand PurchaseOrderUpdateIntegrationTest.dod;
    
    @Test
    public void PurchaseOrderUpdateIntegrationTest.testCountPurchaseOrderUpdates() {
        Assert.assertNotNull("Data on demand for 'PurchaseOrderUpdate' failed to initialize correctly", dod.getRandomPurchaseOrderUpdate());
        long count = PurchaseOrderUpdate.countPurchaseOrderUpdates();
        Assert.assertTrue("Counter for 'PurchaseOrderUpdate' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PurchaseOrderUpdateIntegrationTest.testFindPurchaseOrderUpdate() {
        PurchaseOrderUpdate obj = dod.getRandomPurchaseOrderUpdate();
        Assert.assertNotNull("Data on demand for 'PurchaseOrderUpdate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PurchaseOrderUpdate' failed to provide an identifier", id);
        obj = PurchaseOrderUpdate.findPurchaseOrderUpdate(id);
        Assert.assertNotNull("Find method for 'PurchaseOrderUpdate' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PurchaseOrderUpdate' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PurchaseOrderUpdateIntegrationTest.testFindAllPurchaseOrderUpdates() {
        Assert.assertNotNull("Data on demand for 'PurchaseOrderUpdate' failed to initialize correctly", dod.getRandomPurchaseOrderUpdate());
        long count = PurchaseOrderUpdate.countPurchaseOrderUpdates();
        Assert.assertTrue("Too expensive to perform a find all test for 'PurchaseOrderUpdate', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PurchaseOrderUpdate> result = PurchaseOrderUpdate.findAllPurchaseOrderUpdates();
        Assert.assertNotNull("Find all method for 'PurchaseOrderUpdate' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PurchaseOrderUpdate' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PurchaseOrderUpdateIntegrationTest.testFindPurchaseOrderUpdateEntries() {
        Assert.assertNotNull("Data on demand for 'PurchaseOrderUpdate' failed to initialize correctly", dod.getRandomPurchaseOrderUpdate());
        long count = PurchaseOrderUpdate.countPurchaseOrderUpdates();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PurchaseOrderUpdate> result = PurchaseOrderUpdate.findPurchaseOrderUpdateEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PurchaseOrderUpdate' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PurchaseOrderUpdate' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PurchaseOrderUpdateIntegrationTest.testFlush() {
        PurchaseOrderUpdate obj = dod.getRandomPurchaseOrderUpdate();
        Assert.assertNotNull("Data on demand for 'PurchaseOrderUpdate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PurchaseOrderUpdate' failed to provide an identifier", id);
        obj = PurchaseOrderUpdate.findPurchaseOrderUpdate(id);
        Assert.assertNotNull("Find method for 'PurchaseOrderUpdate' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPurchaseOrderUpdate(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PurchaseOrderUpdate' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PurchaseOrderUpdateIntegrationTest.testMergeUpdate() {
        PurchaseOrderUpdate obj = dod.getRandomPurchaseOrderUpdate();
        Assert.assertNotNull("Data on demand for 'PurchaseOrderUpdate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PurchaseOrderUpdate' failed to provide an identifier", id);
        obj = PurchaseOrderUpdate.findPurchaseOrderUpdate(id);
        boolean modified =  dod.modifyPurchaseOrderUpdate(obj);
        Integer currentVersion = obj.getVersion();
        PurchaseOrderUpdate merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PurchaseOrderUpdate' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PurchaseOrderUpdateIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PurchaseOrderUpdate' failed to initialize correctly", dod.getRandomPurchaseOrderUpdate());
        PurchaseOrderUpdate obj = dod.getNewTransientPurchaseOrderUpdate(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PurchaseOrderUpdate' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PurchaseOrderUpdate' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'PurchaseOrderUpdate' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PurchaseOrderUpdateIntegrationTest.testRemove() {
        PurchaseOrderUpdate obj = dod.getRandomPurchaseOrderUpdate();
        Assert.assertNotNull("Data on demand for 'PurchaseOrderUpdate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PurchaseOrderUpdate' failed to provide an identifier", id);
        obj = PurchaseOrderUpdate.findPurchaseOrderUpdate(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PurchaseOrderUpdate' with identifier '" + id + "'", PurchaseOrderUpdate.findPurchaseOrderUpdate(id));
    }
    
}
