// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cs.ut.domain;

import cs.ut.domain.HireRequestStatus;
import cs.ut.domain.Plant;
import cs.ut.domain.PlantDataOnDemand;
import cs.ut.domain.PurchaseOrder;
import cs.ut.domain.PurchaseOrderDataOnDemand;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PurchaseOrderDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PurchaseOrderDataOnDemand: @Component;
    
    private Random PurchaseOrderDataOnDemand.rnd = new SecureRandom();
    
    private List<PurchaseOrder> PurchaseOrderDataOnDemand.data;
    
    @Autowired
    PlantDataOnDemand PurchaseOrderDataOnDemand.plantDataOnDemand;
    
    public PurchaseOrder PurchaseOrderDataOnDemand.getNewTransientPurchaseOrder(int index) {
        PurchaseOrder obj = new PurchaseOrder();
        setEndDate(obj, index);
        setPlant(obj, index);
        setStartDate(obj, index);
        setStatus(obj, index);
        setTotalCost(obj, index);
        return obj;
    }
    
    public void PurchaseOrderDataOnDemand.setEndDate(PurchaseOrder obj, int index) {
        Date endDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setEndDate(endDate);
    }
    
    public void PurchaseOrderDataOnDemand.setPlant(PurchaseOrder obj, int index) {
        Plant plant = plantDataOnDemand.getRandomPlant();
        obj.setPlant(plant);
    }
    
    public void PurchaseOrderDataOnDemand.setStartDate(PurchaseOrder obj, int index) {
        Date startDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setStartDate(startDate);
    }
    
    public void PurchaseOrderDataOnDemand.setStatus(PurchaseOrder obj, int index) {
        HireRequestStatus status = HireRequestStatus.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
    public void PurchaseOrderDataOnDemand.setTotalCost(PurchaseOrder obj, int index) {
        BigDecimal totalCost = BigDecimal.valueOf(index);
        obj.setTotalCost(totalCost);
    }
    
    public PurchaseOrder PurchaseOrderDataOnDemand.getSpecificPurchaseOrder(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PurchaseOrder obj = data.get(index);
        Long id = obj.getId();
        return PurchaseOrder.findPurchaseOrder(id);
    }
    
    public PurchaseOrder PurchaseOrderDataOnDemand.getRandomPurchaseOrder() {
        init();
        PurchaseOrder obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return PurchaseOrder.findPurchaseOrder(id);
    }
    
    public boolean PurchaseOrderDataOnDemand.modifyPurchaseOrder(PurchaseOrder obj) {
        return false;
    }
    
    public void PurchaseOrderDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = PurchaseOrder.findPurchaseOrderEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PurchaseOrder' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PurchaseOrder>();
        for (int i = 0; i < 10; i++) {
            PurchaseOrder obj = getNewTransientPurchaseOrder(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
