// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cs.ut.domain;

import cs.ut.domain.PurchaseOrderIntegrationTest;
import java.util.Iterator;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.runner.RunWith;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect PurchaseOrderIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PurchaseOrderIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
}
